// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const LoginLazyImport = createFileRoute('/login')()
const EditItemLazyImport = createFileRoute('/editItem')()
const DeleteItemLazyImport = createFileRoute('/deleteItem')()
const AdminLazyImport = createFileRoute('/admin')()
const AddItemLazyImport = createFileRoute('/addItem')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const EditItemLazyRoute = EditItemLazyImport.update({
  path: '/editItem',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/editItem.lazy').then((d) => d.Route))

const DeleteItemLazyRoute = DeleteItemLazyImport.update({
  path: '/deleteItem',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/deleteItem.lazy').then((d) => d.Route))

const AdminLazyRoute = AdminLazyImport.update({
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin.lazy').then((d) => d.Route))

const AddItemLazyRoute = AddItemLazyImport.update({
  path: '/addItem',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/addItem.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/addItem': {
      preLoaderRoute: typeof AddItemLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      preLoaderRoute: typeof AdminLazyImport
      parentRoute: typeof rootRoute
    }
    '/deleteItem': {
      preLoaderRoute: typeof DeleteItemLazyImport
      parentRoute: typeof rootRoute
    }
    '/editItem': {
      preLoaderRoute: typeof EditItemLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AddItemLazyRoute,
  AdminLazyRoute,
  DeleteItemLazyRoute,
  EditItemLazyRoute,
  LoginLazyRoute,
])
