openapi: 3.0.1
info:
  title: Heir-Time Api
  description: An ASP.NET Core Web API for managing inheritance
  version: v1
paths:
  '/api/Item/{id}':
    get:
      tags:
        - Item
      summary: Get an item
      parameters:
        - name: id
          in: path
          description: ''
          required: true
          schema:
            type: integer
            format: int32
        - name: projectId
          in: query
          description: ''
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Item'
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
            text/json:
              schema:
                $ref: '#/components/schemas/Item'
    delete:
      tags:
        - Item
      summary: Deletes a file
      parameters:
        - name: id
          in: path
          description: ''
          required: true
          schema:
            type: integer
            format: int32
        - name: projectId
          in: query
          description: ''
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: integer
                format: int32
            application/json:
              schema:
                type: integer
                format: int32
            text/json:
              schema:
                type: integer
                format: int32
  /api/Item:
    get:
      tags:
        - Item
      summary: Get all items from project
      parameters:
        - name: projectId
          in: query
          description: ''
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
    post:
      tags:
        - Item
      summary: Create a new item with file
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                itemWithFileInput:
                  type: string
                file:
                  type: string
                  format: binary
            encoding:
              itemWithFileInput:
                style: form
              file:
                style: form
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Item'
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
            text/json:
              schema:
                $ref: '#/components/schemas/Item'
    put:
      tags:
        - Item
      summary: Update item and file
      parameters:
        - name: projectId
          in: query
          description: ''
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                itemJson:
                  type: string
                file:
                  type: string
                  format: binary
            encoding:
              itemJson:
                style: form
              file:
                style: form
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Item'
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
            text/json:
              schema:
                $ref: '#/components/schemas/Item'
  /api/Item/bid:
    put:
      tags:
        - Item
      summary: Update bit on item
      parameters:
        - name: projectId
          in: query
          description: ''
          schema:
            type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BidInput'
          text/json:
            schema:
              $ref: '#/components/schemas/BidInput'
          application/*+json:
            schema:
              $ref: '#/components/schemas/BidInput'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Item'
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
            text/json:
              schema:
                $ref: '#/components/schemas/Item'
  /api/Item/winner:
    put:
      tags:
        - Item
      summary: Set the winner of the item
      parameters:
        - name: projectId
          in: query
          description: ''
          schema:
            type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WinnerInput'
          text/json:
            schema:
              $ref: '#/components/schemas/WinnerInput'
          application/*+json:
            schema:
              $ref: '#/components/schemas/WinnerInput'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Item'
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
            text/json:
              schema:
                $ref: '#/components/schemas/Item'
  /api/Project:
    get:
      tags:
        - Project
      summary: Get the user's projects
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
    post:
      tags:
        - Project
      summary: Create a new project
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
          text/json:
            schema:
              $ref: '#/components/schemas/Project'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Project'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Project'
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
            text/json:
              schema:
                $ref: '#/components/schemas/Project'
  '/api/Project/{projectId}':
    get:
      tags:
        - Project
      summary: Get a specific project
      parameters:
        - name: projectId
          in: path
          description: ''
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Project'
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
            text/json:
              schema:
                $ref: '#/components/schemas/Project'
    delete:
      tags:
        - Project
      summary: Delete a project
      parameters:
        - name: projectId
          in: path
          description: ''
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
  /api/User/me:
    get:
      tags:
        - User
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/User'
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            text/json:
              schema:
                $ref: '#/components/schemas/User'
  '/api/User/{email}':
    get:
      tags:
        - User
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/User'
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            text/json:
              schema:
                $ref: '#/components/schemas/User'
  /api/User:
    get:
      tags:
        - User
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /api/User/login:
    post:
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
          text/json:
            schema:
              $ref: '#/components/schemas/Login'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        '200':
          description: Success
  /api/User/logout:
    get:
      tags:
        - User
      responses:
        '200':
          description: Success
  /api/User/register:
    post:
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          text/json:
            schema:
              $ref: '#/components/schemas/User'
          application/*+json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/User'
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            text/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    Bid:
      type: object
      properties:
        value:
          type: integer
          format: int32
        receivingDate:
          type: string
          format: date-time
        user:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time
          nullable: true
      additionalProperties: false
    BidInput:
      type: object
      properties:
        value:
          type: integer
          format: int32
        itemId:
          type: integer
          format: int32
        receivingDate:
          type: string
          nullable: true
      additionalProperties: false
    Item:
      type: object
      properties:
        id:
          type: integer
          format: int32
          nullable: true
        title:
          type: string
          nullable: true
        releaseDate:
          type: string
          format: date-time
        itemStatus:
          $ref: '#/components/schemas/Status'
        statusName:
          type: string
          nullable: true
          readOnly: true
        description:
          type: string
          nullable: true
        location:
          type: string
          nullable: true
        fileUrls:
          type: array
          items:
            type: string
          nullable: true
        fileKeys:
          type: array
          items:
            type: string
          nullable: true
        recipient:
          type: string
          nullable: true
        bids:
          type: array
          items:
            $ref: '#/components/schemas/Bid'
          nullable: true
      additionalProperties: false
      description: Item to be auctioned off
    Login:
      type: object
      properties:
        emailAddress:
          type: string
          nullable: true
        password:
          type: string
          nullable: true
      additionalProperties: false
    Project:
      type: object
      properties:
        id:
          type: string
          nullable: true
        projectName:
          type: string
          nullable: true
        owner:
          type: string
          nullable: true
        admins:
          type: array
          items:
            type: string
          nullable: true
        users:
          type: array
          items:
            type: string
          nullable: true
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'
          nullable: true
      additionalProperties: false
    Status:
      enum:
        - 0
        - 1
        - 2
      type: integer
      format: int32
    User:
      type: object
      properties:
        id:
          type: string
          nullable: true
        firstName:
          type: string
          nullable: true
        lastName:
          type: string
          nullable: true
        emailAddress:
          type: string
          nullable: true
        password:
          type: string
          nullable: true
        isAdmin:
          type: boolean
          nullable: true
        ownedProjects:
          type: array
          items:
            type: string
          nullable: true
        projects:
          type: array
          items:
            type: string
          nullable: true
        phoneNumber:
          type: string
          nullable: true
        address:
          type: string
          nullable: true
      additionalProperties: false
    WinnerInput:
      type: object
      properties:
        userId:
          type: string
          nullable: true
        itemId:
          type: integer
          format: int32
      additionalProperties: false
