# docker build -t nginx .
# docker run -p 80:80 nginx
FROM node:20 AS node_build

WORKDIR /app

COPY package.json package-lock.json ./
COPY nginx.conf ./nginx.conf
RUN corepack enable pnpm
RUN pnpm install


COPY . .
RUN npm run build

FROM nginx:latest

COPY --from=node_build /app/build /usr/share/nginx/html
COPY --from=node_build /app/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]