FROM node:20 AS node_build

WORKDIR /app

COPY ./environments /app/environments
COPY ./src /app/src
COPY ./public /app/public
COPY ./index.html /app/index.html
COPY ./package*.json /app
COPY ./vite.config.ts /app
COPY ./tsconfig*.json /app

RUN npm i

RUN npm run build

FROM nginx:latest

COPY --from=node_build /app/dist /usr/share/nginx/html