version: "3"

services:
  dotnet-api:
    image: mcr.microsoft.com/devcontainers/dotnet:1-8.0-bookworm
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    links:
      - node-app
      - mongo
    networks:
      - app-network

  node-app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    networks:
      - app-network

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./db
        target: /data/db
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

networks:
  app-network:
    driver: bridge
